apiVersion: apps/v1
kind: Deployment
metadata:
  name: garnet
  labels:
    app.kubernetes.io/name: garnet
    app.kubernetes.io/component: garnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: garnet
      app.kubernetes.io/component: garnet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: garnet
        app.kubernetes.io/component: garnet
    spec:
      containers:
        - name: garnet
          image: ghcr.io/microsoft/garnet
          ports:
            - name: resp
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: resp
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: resp
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
