-- Postgres deferred delete gates have no SQLite equivalent; local SQLite mutations use the same adapter-level reliability boundary.
-- Intentionally empty: this migration keeps local and Postgres version histories aligned.
