[package]
name = "shardline-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/shardline-auth"
readme = "../../README.md"
description = "Token signing and verification for Shardline authentication."
publish = true

[dependencies]
shardline-protocol.workspace = true
thiserror.workspace = true
subtle.workspace = true
tracing.workspace = true

[dev-dependencies]
hex.workspace = true
serde_json.workspace = true

[lints]
workspace = true
