[package]
name = "shardline-bench"
edition.workspace = true
license.workspace = true

[[bench]]
name = "reconstruction"
harness = false

[dependencies]
serde_json.workspace = true
shardline-index.workspace = true
shardline-protocol.workspace = true
shardline-server-core.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true
