apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shardline

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - networkpolicy-default-deny-ingress.yaml
  - networkpolicy-allow-ingress-nginx.yaml
  - networkpolicy-allow-monitoring.yaml
  - api-service.yaml
  - api-deployment.yaml
  - api-pdb.yaml
  - api-hpa.yaml
  - transfer-service.yaml
  - transfer-deployment.yaml
  - transfer-pdb.yaml
  - transfer-hpa.yaml
  - gc-cronjob.yaml
  - ingress-nginx.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: shardline
      app.kubernetes.io/part-of: shardline
